version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:8000"
  react:
    build: ./appointify-ui
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"