# Generated by Django 4.2.1 on 2023-05-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointifyuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
    ]
