# Generated by Django 4.2.1 on 2023-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointment_doctor_alter_appointment_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointifyuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
