# Generated by Django 4.2.1 on 2023-05-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_alter_appointifyuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
    ]
