# Generated by Django 4.2.1 on 2023-05-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_alter_doctor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ("slot",),
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
            },
        ),
    ]
